server:
  port: 11001
spring:
  application:
    name: "provide-serve"
    admin:
      enabled: false
eureka:
  instance:
    prefer-ip-address: true
    instance-id: "userService02"
#    instance-id: ${spring.cloud.client.ip-address}:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15
  client:
    service-url:
      defaultZone: "http://eurekaServer18000:18000/eureka/,http://eurekaServer18001:18001/eureka/"